source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'moped'
gem 'useragent'
gem 'slim'
gem 'geoip'
gem 'hashids'
gem 'puma'
gem 'redis'
gem 'bunny'
gem 'newrelic_rpm'
gem 'sinatra-subdomain'
